In [1]:
import pandas as pd
from datetime import date
from datetime import date, timedelta
import json
from urllib.request import urlopen
import requests
import time
import glob
import os

In [2]:
for root, _, files in os.walk('NewData'):
        for file in files:
            if file.endswith('.csv') or file.endswith('.xlsx'):
                os.remove(os.path.join(root, file))
                print(f'{os.path.join(root, file)} Deleted!')

NewData\2023-11-24-All Meetings.csv Deleted!
NewData\2023-11-24-All Meetings.xlsx Deleted!
NewData\2023-11-24-CarrotCrusher.csv Deleted!
NewData\2nd Last Run-Form.csv Deleted!
NewData\3nd Last Run-Form.csv Deleted!
NewData\CarrotCruncherModelUpdate.csv Deleted!
NewData\CleanedForm\2023-11-24-All Meetings - Form.csv Deleted!
NewData\Fields\2023-11-24 - Fields.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Bong Bong - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Cairns - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Canterbury - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Moonee Valley - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Muswellbrook - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Naracoorte - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-New Plymouth Raceway - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Orange - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Sunshine Coast - Field.csv Deleted!
NewData\Fields\MeetingFields\2023-11-24-Wodonga - Field.csv Deleted!
NewData\Form\2023-11-24-All Meetings.csv Deleted!
NewData\Form\ExcelFiles\2023-11-24-All Meetings.xlsx Deleted!
NewData\JockeySR\2023-11-24 - Jockeys SR.csv Deleted!
NewData\MeetingFiles\2023-11-24-Bong Bong-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Cairns-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Canterbury-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Moonee Valley-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Muswellbrook-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Naracoorte-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-New Plymouth Raceway-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Orange-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Sunshine Coast-Ratings.csv Deleted!
NewData\MeetingFiles\2023-11-24-Wodonga-Ratings.csv Deleted!
NewData\Ratings\2023-11-24 - RatingsSheet.csv Deleted!
NewData\Test\2023-11-24-TestFile.csv Deleted!
NewData\TrainerSR\2023-11-24 - Trainers SR.csv Deleted!

In [3]:
today = date.today()
rundate = today + timedelta(days=0)
dte = rundate.strftime('%d-%m-%Y')
etd = rundate.strftime('%Y-%m-%d')
date1 = etd
date = dte
fldr = etd
etd

'2023-12-22'

In [4]:

api = '?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed'

jkyurl = "https://www.puntingform.com.au/api/formdataservice/GetJockeyStrikeRateData/"

trnurl = "https://www.puntingform.com.au/api/formdataservice/GetTrainerStrikeRateData/"

jky = 'Jockeys SR'
JkySR = jkyurl+dte+api

trn = 'Trainers SR'
TrnSR = trnurl+dte+api

jkysr = pd.read_csv(JkySR, index_col=False)
jkysr = jkysr.sort_values(by=['L100ExpWins'], ascending=False)
jkysr.to_csv(f"./NewData/JockeySR/{etd} - %s.csv"%jky, index=False)
jkysr

,MeetingDate,JockeyID,JockeyName,CareerWins,CareerRuns,CareerPlc2,CareerPlc3,L100Wins,L100Runs,L100Plc2,L100Plc3,CareerExpWins,CareerPL,CareerTO,L100ExpWins,L100PL,L100To
88,22-Dec-2023,14417,Ashley Butler,466,2135,354,263,20,100,20,9,423.71,-761.13,81478.75,22.28,-758.45,4677.03
172,22-Dec-2023,17323,McKenzie Apel,26,118,17,17,22,100,14,15,24.92,-563.26,4693.42,21.55,-495.43,4038.92
211,22-Dec-2023,15543,Clayton Gallagher,527,3409,426,396,35,100,7,12,466.85,3.15,78429.11,21.54,1755.42,4643.04
225,22-Dec-2023,16684,Jasper Franklin,102,608,79,68,17,100,18,12,99.76,-1631.41,17491.72,20.52,-878.70,4323.82
26,22-Dec-2023,10533,D R Beasley,250,1665,177,150,21,100,13,12,236.39,-2102.21,40559.40,20.36,-539.96,4021.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,22-Dec-2023,17271,Danica Munro,1,11,1,3,1,11,1,3,1.06,-22.53,142.53,1.06,-22.53,142.53
193,22-Dec-2023,17400,Beau Treloar,1,14,0,3,1,14,0,3,0.94,-12.03,125.02,0.94,-12.03,125.02
181,22-Dec-2023,16427,T Ladd,1,7,1,0,1,7,1,0,0.52,44.03,67.73,0.52,44.03,67.73
240,22-Dec-2023,16564,Darragh Keenan,0,8,0,1,0,8,0,1,0.29,-35.23,35.23,0.29,-35.23,35.23
245,22-Dec-2023,16948,Ms C Ferris,0,1,0,0,0,1,0,0,0.06,-5.26,5.26,0.06,-5.26,5.26

In [5]:
trnsr = pd.read_csv(TrnSR, index_col=False)
trnsr = trnsr.sort_values(by=['L100Wins'], ascending=False)
trnsr.to_csv(f"./NewData/TrainerSR/{etd} - %s.csv"%trn, index=False)
trnsr

,MeetingDate,TrainerID,TrainerName,CareerWins,CareerRuns,CareerPlc2,CareerPlc3,L100Wins,L100Runs,L100Plc2,L100Plc3,CareerExpWins,CareerPL,CareerTO,L100ExpWins,L100PL,L100To
344,22-Dec-2023,27250,Clinton Taylor,208,719,148,100,28,100,22,15,204.26,-4268.20,50489.43,30.13,-632.10,7376.58
179,22-Dec-2023,25503,Adam Trinder,435,2583,362,337,26,100,16,16,431.23,-7739.05,74836.42,22.39,-214.98,4473.85
430,22-Dec-2023,28514,P C Ng,78,711,54,69,25,100,6,8,67.31,24.71,10114.74,14.20,1239.16,2215.26
349,22-Dec-2023,27283,Toni Schofield,58,281,39,42,24,100,14,15,56.77,-1054.57,10484.21,23.15,-323.46,4288.89
400,22-Dec-2023,27673,Brett Robb,167,989,138,112,23,100,7,12,162.60,-3128.32,28918.11,14.42,915.39,2359.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,22-Dec-2023,17206,G C Oakes,0,35,2,1,0,35,2,1,2.11,-327.50,327.50,2.11,-327.50,327.50
396,22-Dec-2023,27607,Shae Norton,0,6,0,0,0,6,0,0,0.08,-8.92,8.92,0.08,-8.92,8.92
227,22-Dec-2023,23412,Ms E Faust,6,192,10,23,0,100,3,13,10.96,-702.27,1405.06,5.24,-693.72,693.72
392,22-Dec-2023,28597,Jackson Matthews,0,6,1,0,0,6,1,0,0.62,-84.19,84.19,0.62,-84.19,84.19
277,22-Dec-2023,28451,A C Rolston,0,3,0,0,0,3,0,0,0.06,-6.77,6.77,0.06,-6.77,6.77

In [6]:
mtgsurl = 'https://www.puntingform.com.au/api/formdataservice/GetMeetings/'
ratingsurl = "https://www.puntingform.com.au/api/ratingsservice/GetRatingsText"

mtgs_url = (mtgsurl + date + api)
response = urlopen(mtgs_url)

data_json = json.loads(response.read())
df = pd.DataFrame(data_json)
df

                              Key                Value
0              lismore-22-12-2023              Lismore
1               mackay-22-12-2023               Mackay
2           cranbourne-22-12-2023           Cranbourne
3           yarra-glen-22-12-2023           Yarra Glen
4              oakbank-22-12-2023              Oakbank
5             matamata-22-12-2023             Matamata
6  devonport-synthetic-22-12-2023  Devonport Synthetic
7      wagga-riverside-22-12-2023      Wagga Riverside

In [7]:
track_names = df['Value']
fns = track_names.tolist()

track = df['Value'].str.replace(' ', '%20')
track_list = track.tolist()
team = track_list

ratingsurl = [f'{ratingsurl}/{t}/{date}{api}' for t in team]

inputs = zip(ratingsurl, fns)

def download_url(args):
    ratingsurl, fn = args[0], args[1]
    try:
        r = requests.get(ratingsurl)
        with open(f'./NewData/MeetingFiles/%s-{fn}-Ratings.csv'%date1, 'wb') as f:
            f.write(r.content)
        print(ratingsurl, time.time())
    except Exception as e:
        print('Exception in download_url():', e)

t0 = time.time()
for i in inputs:
    result = download_url(i)

https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Lismore/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248811.1647782
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Mackay/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248814.6798644
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Cranbourne/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248816.7943745
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Yarra%20Glen/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248819.2053506
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Oakbank/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248821.2431328
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Matamata/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248823.6126432
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Devonport%20Synthetic/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248825.9455175
https://www.puntingform.com.au/api/ratingsservice/GetRatingsText/Wagga%20Riverside/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248827.939856

In [8]:
path = f'./NewData/MeetingFiles/'

all_files = glob.glob(path + date1+'*-Ratings.csv')

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=False, header=0)
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=False)

df.drop(['PdfPath', 'PublishTime'], axis=1, inplace=True)
df.rename(columns={'ClsDiff': 'Class Change', 'RunStyle': 'Historical Run Style', 'PrSe': 'Predicted Settling Position', 'PFScore': 'PF Score 0-100', 'AHSP': 'Average Historical Settling Pos %', 'RPP': 'Neural Price', 'RPR': 'Neural Rank', 'ScRank': 'Last 600m Ranking Late Speed', 'WP20R': 'Weight Class Rank', 'TP20R': 'Time Ranking Start to Finish', 'WPTP20R': 'Time Adjust - Weight/Class Rank', 'ETRPrRk': 'Early Time Ranking to 600m Speed'}, inplace=True)

df.replace([900,25], '-', inplace=True)

df.to_csv('./NewData/Ratings/%s - RatingsSheet.csv' %date1, index=False)
df

,Meeting,RaceNo,TrackCondition,HorseName,TabNo,Barrier,Reliable,Class Change,Historical Run Style,Predicted Settling Position,...,SPrice,TP20P,Time Ranking Start to Finish,WP20P,Weight Class Rank,WPTP20P,Time Adjust - Weight/Class Rank,ETRPrice,Early Time Ranking to 600m Speed,HorseId
0,Cranbourne,1,Good,Core Concept,1,5,False,0.0,no data,-,...,-,-,-,-,-,-,-,-,-,986678
1,Cranbourne,1,Good,Dark Journey,2,2,False,0.0,no data,-,...,-,-,-,-,-,-,-,-,-,980888
2,Cranbourne,1,Good,Presides,4,6,False,0.0,no data,-,...,-,-,-,-,-,-,-,-,-,964782
3,Cranbourne,1,Good,Abovethefrostline,5,3,False,0.0,no data,-,...,-,-,-,-,-,-,-,-,-,975139
4,Cranbourne,1,Good,I Miss Margie,7,9,False,0.0,l,1,...,-,1.58,1,10.71,3,2.75,2,2.41,2,975511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Yarra Glen,9,Good,Zipitup,6,8,True,-0.2,op/mf,8,...,5.69,11.44,5,14.29,3,12.71,5,20.48,6,943011
82,Yarra Glen,9,Good,Tom The Star,7,2,True,-0.2,op,3,...,141.56,102.59,8,42.32,7,59.92,7,8.11,3,883324
83,Yarra Glen,9,Good,Gold Manuka,8,7,True,0.0,op,4,...,17.51,4.93,2,15.3,4,7.46,2,8.13,4,946253
84,Yarra Glen,9,Good,Carry On Camping,12,9,True,6.3,op,6,...,-,83.99,7,274.57,9,128.63,8,-,-,940441
85,Yarra Glen,9,Good,Steady Jam,13,3,True,0.0,op,5,...,45.13,2.32,1,1.67,1,1.94,1,121.84,8,929556

In [9]:
Fieldsurl = 'https://www.puntingform.com.au/api/formdataservice/GetFields'

Fieldsurl = [f'{Fieldsurl}/{t}/{dte}{api}' for t in team]

inputs = zip(Fieldsurl, fns)

def download_url(args):
    Fieldsurl, fn = args[0], args[1]
    try:
        r = requests.get(Fieldsurl)
        with open(f'./NewData/Fields/MeetingFields/{etd}-{fn} - Field.csv', 'wb') as f:
            f.write(r.content)
        print(Fieldsurl, time.time())
    except Exception as e:
        print('Exception in download_url():', e)

t0 = time.time()
for i in inputs:
    result = download_url(i)

https://www.puntingform.com.au/api/formdataservice/GetFields/Lismore/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248932.365372
https://www.puntingform.com.au/api/formdataservice/GetFields/Mackay/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248934.982765
https://www.puntingform.com.au/api/formdataservice/GetFields/Cranbourne/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248937.0270224
https://www.puntingform.com.au/api/formdataservice/GetFields/Yarra%20Glen/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248939.2471852
https://www.puntingform.com.au/api/formdataservice/GetFields/Oakbank/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248941.3289256
https://www.puntingform.com.au/api/formdataservice/GetFields/Matamata/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248943.4212127
https://www.puntingform.com.au/api/formdataservice/GetFields/Devonport%20Synthetic/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248945.4544618
https://www.puntingform.com.au/api/formdataservice/GetFields/Wagga%20Riverside/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed 1703248947.5225823

In [10]:
from pandas.errors import EmptyDataError
import glob
import warnings
warnings.filterwarnings('ignore')

path = f'./NewData/Fields/MeetingFields/' # use your pathC:\Users\bjj07\OneDrive\2. VSCFiles\3_Horse Racing\Testing\In Work\GetFormText
all_files = glob.glob(path + f"/{etd}*.csv")

li = []
bad_files = []

for filename in all_files:
    try:
        df = pd.read_csv(filename, index_col=False, header=0)
        li.append(df)

    except EmptyDataError:
        print(f'No columns to parse from file {filename}')
        bad_files.append(filename)


df = pd.concat(li, axis=0, ignore_index=False)

results = etd + ' - Fields'

df.to_csv('./NewData/Fields/%s.csv' %results)
df

,Race Number,Tab Number,Horse,Weight,Claim,Barrier,Jockey,Trainer,RaceId,HorseId,JockeyId,TrainerId,FormId
0,1,1,Core Concept,58.0,0.0,5,Jamie Mott,Mark Ashby,1123361,986678,13251,25502,7929188
1,1,2,Dark Journey,58.0,0.0,2,Daniel Moor,Jason Warren,1123361,980888,13066,22610,7929189
2,1,4,Presides,58.0,0.0,6,Jye Mc Neil,James Cummings,1123361,964782,14936,26597,7929191
3,1,5,Abovethefrostline,56.0,0.0,3,B Mc Dougall,Marcus Fahler,1123361,975139,15279,13892,7929192
4,1,7,I Miss Margie,56.0,0.0,9,Luke Currie,T Busuttin & N Young,1123361,975511,11407,26753,7929194
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,9,6,Zipitup,56.5,4.0,7,Beau Treloar,Thomas Conlan,1123481,943011,17400,27444,7930537
80,9,7,Tom The Star,58.0,2.0,1,Thomas Prebble,Matthew Cumani,1123481,883324,17083,26723,7930538
81,9,8,Gold Manuka,59.5,0.0,6,Rhys Mc Leod,Jason Warren,1123481,946253,11899,22610,7930539
82,9,12,Carry On Camping,55.0,0.0,8,Harry Grace,M R Sharp,1123481,940441,15607,20339,7930543
83,9,13,Steady Jam,52.0,2.0,2,Lauren Burke,D P Dwyer,1123481,929556,17378,18271,7930544

In [11]:
Formurl = 'https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText'

raceno = [*range(1,13,1)]

Formurls = [f'{Formurl}/{t}/{r}/{dte}{api}' for t in team for r in raceno]

import requests
import time

fns = [f'./NewData/Form/TempFiles/Form-{t}-R{r}.csv' for t in team for r in raceno]

inputs = zip(Formurls, fns)

def download_url(args):
    t0 = time.time()
    Formurl, fn = args[0], args[1]
    try:
        r = requests.get(Formurl)
        with open(fn, 'wb') as f:
            f.write(r.content)
        return(Formurl, time.time() - t0)
    except Exception as e:
        print('Exception in download_url():', e)

t0 = time.time()
for i in inputs:
    result = download_url(i)
    print('url:', result[0], 'time:', result[1])
print('Total time:', time.time() - t0)

url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.8520569801330566
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8226869106292725
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.237668037414551
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.207359790802002
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.846505641937256
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8150250911712646
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.869802236557007
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.9151785373687744
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 1.9750678539276123
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.026517629623413
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.08386492729187
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Lismore/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.2168662548065186
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.087440013885498
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.5199902057647705
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.3926336765289307
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.726245880126953
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.9018521308898926
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.821051597595215
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.396162509918213
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.4339370727539062
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.860590934753418
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.088700771331787
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.085232734680176
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Mackay/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.965317487716675
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0275304317474365
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.6075096130371094
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.3958494663238525
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.355031728744507
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.4735207557678223
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.81451153755188
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.7866249084472656
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.2969565391540527
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.01811146736145
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0576887130737305
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.018491744995117
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Cranbourne/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.382559061050415
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 5.415395498275757
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0406992435455322
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.4766221046447754
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.7981534004211426
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8615801334381104
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.852649211883545
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8135340213775635
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.4375569820404053
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.3818883895874023
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.277320623397827
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.1530497074127197
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Yarra%20Glen/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.686255693435669
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.778008222579956
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.263026237487793
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.1186914443969727
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.7885870933532715
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8292760848999023
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8808629512786865
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.9458940029144287
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.5624802112579346
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.1614747047424316
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.027799606323242
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.052088737487793
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Oakbank/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.171556234359741
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.7489452362060547
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.6024043560028076
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.4721786975860596
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.5845587253570557
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.008197546005249
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.934072494506836
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.0445871353149414
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8245036602020264
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.6824305057525635
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0943849086761475
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 1.9961731433868408
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Matamata/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.023920774459839
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.154805898666382
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.79712176322937
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.7543766498565674
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.7756967544555664
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.8651018142700195
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.420768976211548
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.9069535732269287
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.5065066814422607
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.1720633506774902
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.30175518989563
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0506341457366943
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Devonport%20Synthetic/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0432145595550537
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/1/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.4798271656036377
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/2/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.961456060409546
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/3/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.0303444862365723
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/4/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.796724557876587
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/5/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.798539161682129
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/6/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.122913360595703
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/7/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.4010045528411865
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/8/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.90346097946167
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/9/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.107130765914917
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/10/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 3.2379965782165527
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/11/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 2.0176920890808105
url: https://www.puntingform.com.au/api/formdataservice/GetExtendedFormText/Wagga%20Riverside/12/22-12-2023?ApiKey=643c2eac-42a7-4909-9f9d-0474593067ed time: 1.9887714385986328
Total time: 256.7778329849243

In [12]:
from pandas.errors import EmptyDataError
import glob
import warnings
warnings.filterwarnings('ignore')

results = etd +'-'+ 'All Meetings'

path = f'./NewData/Form/TempFiles' # use your pathC:\Users\bjj07\OneDrive\2. VSCFiles\3_Horse Racing\Testing\In Work\GetFormText
all_files = glob.glob(path + "/Form*.csv")

li = []
bad_files = []

for filename in all_files:
    try:
        df = pd.read_csv(filename, index_col=False, header=0)
        li.append(df)

    except EmptyDataError:
        print(f'No columns to parse from file {filename}')
        bad_files.append(filename)


df2 = pd.concat(li, axis=0, ignore_index=False)

df2.to_csv('./NewData/Form/%s.csv' %results, index=False)
df2.to_excel('./NewData/Form/ExcelFiles/%s.xlsx' %results, index=False)
df2

No columns to parse from file ./NewData/Form/TempFiles\Form-Cranbourne-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Cranbourne-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Cranbourne-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Cranbourne-R9.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Devonport%20Synthetic-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Devonport%20Synthetic-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Devonport%20Synthetic-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Devonport%20Synthetic-R9.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Lismore-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Lismore-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Lismore-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Lismore-R9.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Mackay-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Mackay-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Mackay-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Matamata-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Matamata-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Matamata-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Oakbank-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Oakbank-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Oakbank-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Oakbank-R8.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Oakbank-R9.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Wagga%20Riverside-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Wagga%20Riverside-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Wagga%20Riverside-R12.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Wagga%20Riverside-R9.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Yarra%20Glen-R10.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Yarra%20Glen-R11.csv
No columns to parse from file ./NewData/Form/TempFiles\Form-Yarra%20Glen-R12.csv

,meeting date,track,race number,start time,distance,age restrictions,class restrictions,weight restrictions,race prizemoney,sex restrictions,...,horse id,horse trainer id,horse jockey id,form trainer id,form jockey id,foal date,prizemoney,sectional,prizemoney won,country
0,22/12/2023 12:00:00 AM,Cranbourne,1,22-Dec-2023 18:15,1000,3yo,Maiden,0.0,Of $40000 - 1st $22000 | 2nd $7200| 3rd $...,NaN,...,975511,26753,11407,26753,12035,20/09/2020,$37500,35.24sec 600m,$6750,AUS
1,22/12/2023 12:00:00 AM,Cranbourne,1,22-Dec-2023 18:15,1000,3yo,Maiden,0.0,Of $40000 - 1st $22000 | 2nd $7200| 3rd $...,NaN,...,975511,26753,11407,26753,12423,20/09/2020,$37500,32.86sec 600m,$1875,AUS
2,22/12/2023 12:00:00 AM,Cranbourne,1,22-Dec-2023 18:15,1000,3yo,Maiden,0.0,Of $40000 - 1st $22000 | 2nd $7200| 3rd $...,NaN,...,975511,26753,11407,26753,12423,20/09/2020,$150000,35.78sec 600m,$3000,AUS
3,22/12/2023 12:00:00 AM,Cranbourne,1,22-Dec-2023 18:15,1000,3yo,Maiden,0.0,Of $40000 - 1st $22000 | 2nd $7200| 3rd $...,NaN,...,975511,26753,11407,26753,16369,20/09/2020,$27000,33.99sec 600m,$4590,AUS
4,22/12/2023 12:00:00 AM,Cranbourne,1,22-Dec-2023 18:15,1000,3yo,Maiden,0.0,Of $40000 - 1st $22000 | 2nd $7200| 3rd $...,NaN,...,975511,26753,11407,26753,12423,20/09/2020,$37500,36.51sec 600m,$3375,AUS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,22/12/2023 12:00:00 AM,Yarra Glen,9,22-Dec-2023 17:30,1009,3yo+,Benchmark 58,54.0,Of $27000 - 1st $14850 | 2nd $4590| 3rd $...,NaN,...,929556,18271,17378,18271,14704,11/11/2017,$16000,34.70sec 600m,$0,AUS
110,22/12/2023 12:00:00 AM,Yarra Glen,9,22-Dec-2023 17:30,1009,3yo+,Benchmark 58,54.0,Of $27000 - 1st $14850 | 2nd $4590| 3rd $...,NaN,...,929556,18271,17378,18271,17071,11/11/2017,$27000,34.48sec 600m,$1215,AUS
111,22/12/2023 12:00:00 AM,Yarra Glen,9,22-Dec-2023 17:30,1009,3yo+,Benchmark 58,54.0,Of $27000 - 1st $14850 | 2nd $4590| 3rd $...,NaN,...,929556,18271,17378,18271,14704,11/11/2017,$27000,35.38sec 600m,$500,AUS
112,22/12/2023 12:00:00 AM,Yarra Glen,9,22-Dec-2023 17:30,1009,3yo+,Benchmark 58,54.0,Of $27000 - 1st $14850 | 2nd $4590| 3rd $...,NaN,...,929556,18271,17378,18271,16120,11/11/2017,$5000,00.00sec 0m,$200,AUS
113,22/12/2023 12:00:00 AM,Yarra Glen,9,22-Dec-2023 17:30,1009,3yo+,Benchmark 58,54.0,Of $27000 - 1st $14850 | 2nd $4590| 3rd $...,NaN,...,929556,18271,17378,18271,16120,11/11/2017,$5000,00.00sec 0m,$200,AUS

In [13]:
import time

time.sleep(5)

files = glob.glob('./NewData/Form/TempFiles/*')
for f in files:
    os.remove(f)

In [14]:
import json
import csv
from numpy import dtype
from datetime import datetime, timedelta
from datetime import date

today = date.today()

currdate2 = today.strftime('%y-%m-%d')
rating = "https://betfair-data-supplier-prod.herokuapp.com/api/widgets/kash-ratings-model/datasets?date=20"+currdate2+"&presenter=RatingsPresenter&csv=true"
Kash=pd.read_csv(rating)
currdate1 = today.strftime('%d/%m/%Y')
Kash["Date"]=currdate1
Kash["meetings.name"]=Kash["meetings.name"].str.title()

Kash.to_csv('NewData/CarrotCruncherModelUpdate.csv',mode='a',index=False)
currdate = datetime.strptime(currdate2,'%y-%m-%d')
currdate += timedelta(days=1)
df = pd.DataFrame(Kash)

df.to_csv(f'NewData/{today}-CarrotCrusher.csv')
df

,meetings.name,meetings.bfExchangeEventId,meetings.races.bfExchangeMarketId,meetings.races.name,meetings.races.number,meetings.races.comment,meetings.races.runners.bfExchangeSelectionId,meetings.races.runners.name,meetings.races.runners.ratedPrice,meetings.races.runners.number,Date
0,Cranbourne,32888404,1.222758,R1 1000m 3yo,1,NaN,5243058,2. Dark Journey,11.81,0,22/12/2023
1,Cranbourne,32888404,1.222758,R1 1000m 3yo,1,NaN,58138564,7. I Miss Margie,5.10,0,22/12/2023
2,Cranbourne,32888404,1.222758,R1 1000m 3yo,1,NaN,63926453,10. Spurline,29.63,0,22/12/2023
3,Cranbourne,32888404,1.222758,R1 1000m 3yo,1,NaN,64121576,1. Core Concept,7.19,0,22/12/2023
4,Cranbourne,32888404,1.222758,R1 1000m 3yo,1,NaN,64121577,4. Presides,3.25,0,22/12/2023
...,...,...,...,...,...,...,...,...,...,...,...
642,Yarra Valley,32888508,1.222759,R9 1009m Hcap,9,NaN,54973900,6. Zipitup,12.85,0,22/12/2023
643,Yarra Valley,32888508,1.222759,R9 1009m Hcap,9,NaN,60735112,1. Machinist,4.09,0,22/12/2023
644,Yarra Valley,32888508,1.222759,R9 1009m Hcap,9,NaN,63122789,12. Carry On Camping,12.64,0,22/12/2023
645,Yarra Valley,32888508,1.222759,R9 1009m Hcap,9,NaN,64122381,2. Graewazi,5.11,0,22/12/2023
646,Yarra Valley,32888508,1.222759,R9 1009m Hcap,9,NaN,64122382,3. Boos Reward,12.52,0,22/12/2023

In [17]:
import numpy as np
np.random.seed(31415)

import warnings
warnings.filterwarnings('ignore')

btdays = 0

today = date.today()
rundate = today - timedelta(days=btdays)
dte = rundate.strftime('%d-%m-%Y')
etd = rundate.strftime('%Y-%m-%d')

formdate = rundate.strftime("%Y%m%d")
track = 'All Meetings'
meeting = etd+'-'+track

form_df = pd.read_csv('./NewData/Form/%s.csv'%meeting)

form_cols = ['meeting date', 'horse sire', 'horse dam', 'horse prize money', 'horse record synthetic', ' form trainer id', ' form jockey id', 'prizemoney', 'prizemoney won', 'country', 'race prizemoney', 'race name', 'jockeys can claim']
form_df.drop(columns=form_cols, inplace=True)

x = 2
form_df1 = form_df.groupby(['horse name', 'track', 'race number']).head(x)


form_df2 = form_df1.drop_duplicates(subset=['horse name', 'track', 'race number'], keep='first')


form_df3 = form_df1.drop_duplicates(subset=['horse name', 'track', 'race number'], keep='last')

form_df3 = form_df3[['race number', 'horse number', 'horse name', 'form barrier', 'form class', 'form distance', 'form jockey', 'form margin', 'form meeting date', 'form other runners', 'form position', 'form price', 'form track', 'form track condition', 'form weight']]

form_df3['form meeting date'] =  pd.to_datetime(form_df3['form meeting date'])
form_df3['form meeting date'] = form_df3['form meeting date'].dt.strftime('%d-%m-%Y')
form_df3['form meeting date'] =form_df3['form meeting date'].apply(pd.to_datetime)
form_df3['DLR-2'] = (pd.to_datetime('today') - form_df3['form meeting date']).dt.days - btdays

form_df3.rename(columns={'horse name':'Horse', 'race number':'Race Number', 'horse number':'Tab Number', 'form position':'Form Pos-2', 'form margin':'Form Margin-2', 'form price':'Form Price-2', 'form barrier':'Form Barrier-2', 'form class':'Form Class-2', 'form distance':'Form Dist-2', 'form jockey':'Form Jky-2', 'form margin':'Form Margin-2',  'form price':'Form Price-2', 'form track':'Form Track-2', 'form track condition':'Form Tr Cond-2', 'form weight':'Form Weight-2', 'form meeting date':'Form Mtg Date-2', 'form other runners':'Form Other Runners-2'}, inplace=True)

form_df3.to_csv('NewData/2nd Last Run-Form.csv', index=False)
form_df3

,Race Number,Tab Number,Horse,Form Barrier-2,Form Class-2,Form Dist-2,Form Jky-2,Form Margin-2,Form Mtg Date-2,Form Other Runners-2,Form Pos-2,Form Price-2,Form Track-2,Form Tr Cond-2,Form Weight-2,DLR-2
1,1,7,I Miss Margie,4,Maiden,1000,C Newitt,2.7,2023-11-23,1-Morning Bright,4,3.1,Ballarat,Good 4,57.0,29
6,1,8,I'm Mim,7,Open,1000,D Moor,8.7,2023-04-01,1-Shesallshenanigans,8,31.0,Bendigo,Good 4,56.0,265
9,1,9,Sakowin,10,Maiden,1100,J Maskiell,1.5,2023-06-15,1-Elderberry,2,6.5,Moe,Soft 7,57.0,190
11,1,12,Aye Aye Skipper,7,Maiden,1112,L Cartwright,3.6,2023-11-11,1-Apppleby,4,4.8,Geelong,Good 4,55.0,41
15,2,1,Beautiful View,3,Maiden,1450,D W Stackhouse,2.0,2023-05-25,1-Shikishi,3,1.8,Kilmore,Soft 5,59.5,211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5839,9,9,Onepointsevengone,9,Bench. 58,1100,R Houston,7.6,2023-11-04,1-Xcessive Gamble,7,11.0,Mortlake,Good 3,57.5,48
5849,9,10,Gracie Turf,4,Bench. 64,1000,P Moloney,2.3,2023-05-15,1-Intisar,5,12.0,Moe,Soft 6,55.0,221
5859,9,11,Just Malcolm,4,Rest. 58,1000,J Bowditch,5.6,2023-03-26,1-Over Boost,8,7.5,Bairnsdale,Good 4,57.5,271
5869,9,12,Carry On Camping,11,Rest. 58,1000,J Duffy,0.2,2023-12-02,1-Chelsea Toff,2,31.0,Yarra Glen,Heavy 10,54.5,20
5879,9,13,Steady Jam,10,Rest. 58,975,L Burke,2.0,2023-11-26,1-Flying Finch,4,16.0,Swan Hill,Good 4,52.0,26

In [18]:
x = 3
form_df4 = form_df.groupby(['horse name', 'track', 'race number']).head(x)
form_df5 = form_df4.drop_duplicates(subset=['horse name', 'track', 'race number'], keep='last')


form_df5.drop(form_df5.loc[form_df5['track']=='track'].index, inplace=True)
form_df6 = form_df5[['race number', 'horse number', 'horse name', 'form barrier', 'form class', 'form distance', 'form jockey', 'form margin', 'form meeting date', 'form other runners', 'form position', 'form price', 'form track', 'form track condition', 'form weight']]
form_df6.rename(columns={'horse name':'Horse', 'race number':'Race Number', 'horse number':'Tab Number', 'form position':'Form Pos-3', 'form margin':'Form Margin-3', 'form price':'Form Price-3', 'form barrier':'Form Barrier-3', 'form class':'Form Class-3', 'form distance':'Form Dist-3', 'form jockey':'Form Jky-3', 'form margin':'Form Margin-3',  'form price':'Form Price-3', 'form track':'Form Track-3', 'form track condition':'Form Tr Cond-3', 'form weight':'Form Weight-3', 'form meeting date':'Form Mtg Date-3', 'form other runners':'Form Other Runners-3'}, inplace=True)

form_df6['Form Mtg Date-3'] =  pd.to_datetime(form_df6['Form Mtg Date-3'])
form_df6['Form Mtg Date-3'] = form_df6['Form Mtg Date-3'].dt.strftime('%d-%m-%Y')
form_df6['Form Mtg Date-3'] =form_df6['Form Mtg Date-3'].apply(pd.to_datetime)
form_df6['DLR-3'] = (pd.to_datetime('today') - form_df6['Form Mtg Date-3']).dt.days - btdays

form_df6.to_csv('NewData/3nd Last Run-Form.csv', index=False)
form_df6

,Race Number,Tab Number,Horse,Form Barrier-3,Form Class-3,Form Dist-3,Form Jky-3,Form Margin-3,Form Mtg Date-3,Form Other Runners-3,Form Pos-3,Form Price-3,Form Track-3,Form Tr Cond-3,Form Weight-3,DLR-3
2,1,7,I Miss Margie,5,Open,1000,C Newitt,10.9,2023-07-29,1-Tiz Enuf,10,21.00,Moonee Valley,Soft 5,54.5,146
7,1,8,I'm Mim,4,Open,1000,C Hefel,2.9,2023-03-15,1-American Zombie,4,31.00,Sandown-Hillside,Good 4,55.0,282
9,1,9,Sakowin,10,Maiden,1100,J Maskiell,1.5,2023-06-15,1-Elderberry,2,6.50,Moe,Soft 7,57.0,190
12,1,12,Aye Aye Skipper,5,Maiden,1000,L Cartwright,3.0,2023-10-28,1-Brazen Style,3,11.00,Yarra Glen,Soft 5,55.0,55
16,2,1,Beautiful View,1,Maiden,1450,W Egan,2.3,2023-05-11,1-Pasheona,2,2.35,Kilmore,Heavy 8,59.5,225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5840,9,9,Onepointsevengone,10,Rest. 58,1000,J Lorensini,1.4,2023-10-21,1-Triumphantly,3,19.00,Bendigo,Good 4,59.0,62
5850,9,10,Gracie Turf,3,Maiden,1000,C Hefel,0.2,2023-04-21,2-Grandma's Plate,1,3.10,Cranbourne,Good 4,58.0,245
5860,9,11,Just Malcolm,3,Bench. 58,1200,J Noonan,11.7,2022-12-29,1-The Hass,11,26.00,Cranbourne,Good 3,58.5,358
5870,9,12,Carry On Camping,2,Bench. 52,1000,S Fawke,1.4,2023-11-25,1-Stirrup,3,61.00,Penshurst,Heavy 8,55.5,27
5880,9,13,Steady Jam,5,Open,1100,S Cooper,0.1,2023-10-28,2-Coupla Days,1,2.30,Harden,Firm 2,66.0,55

In [19]:

form_df2[["Minutes", "Secs"]] = form_df2["form time"].str.split(pat=":", expand=True)
form_df2[["Seconds", "MSecs"]] = form_df2["Secs"].str.split(pat=".", expand=True)
form_df2["Minutes"] = form_df2["Minutes"].astype(int)
form_df2["Seconds"] = form_df2["Seconds"].astype(int)
form_df2["MSecs"] = form_df2["MSecs"].astype(int)
form_df2['Minutes'] = form_df2["Minutes"].apply(lambda x: x*60)
form_df2['MSecs'] = form_df2["MSecs"].apply(lambda x: x/100)
form_df2['Time'] = form_df2["Minutes"] + form_df2["Seconds"]
form_df2['RunTime'] = form_df2["Time"] + form_df2["MSecs"]

form_df2.rename(columns={'horse last10':'horselast10'}, inplace=True)

def inrun(row):
    if row['form position'] == 1:
        val = 0
    elif row['form position'] > 1:
        val = row['form margin']
    else:
        val = 0
    return val
form_df2['margin'] = form_df2.apply(inrun, axis=1)

form_df2["margin"] = form_df2["margin"].astype(float)
form_df2['MarginTime'] = form_df2["margin"].apply(lambda x: x*0.2)
form_df2['RunnerTime'] = form_df2["RunTime"] + form_df2["MarginTime"]

form_df2[["Race Starts", "Race Wins"]] = form_df2["horse record"].str.split(pat=":", expand=True)
form_df2[["Race Wins", "RDrop", "RDrop1"]] = form_df2["Race Wins"].str.split(pat="-", expand=True)

form_df2[["Dist Starts", "Dist Wins"]] = form_df2["horse record distance"].str.split(pat=":", expand=True)
form_df2[["Dist Wins", "DDrop", "DDrop1"]] = form_df2["Dist Wins"].str.split(pat="-", expand=True)

form_df2[["Track Starts", "Track Wins"]] = form_df2["horse record track"].str.split(pat=":", expand=True)
form_df2[["Track Wins", "TDrop", "TDrop1"]] = form_df2["Track Wins"].str.split(pat="-", expand=True)

form_df2[["Tr-Dist Starts", "Tr-Dist Wins"]] = form_df2["horse record track distance"].str.split(pat=":", expand=True)
form_df2[["Tr-Dist Wins", "TDDrop", "TDDrop1"]] = form_df2["Tr-Dist Wins"].str.split(pat="-", expand=True)

form_df2[["Good Starts", "Good Wins"]] = form_df2["horse record good"].str.split(pat=":", expand=True)
form_df2[["Good Wins", "GDrop", "GDrop1"]] = form_df2["Good Wins"].str.split(pat="-", expand=True)
form_df2[["Soft Starts", "Soft Wins"]] = form_df2["horse record soft"].str.split(pat=":", expand=True)
form_df2[["Soft Wins", "SDrop", "SDrop1"]] = form_df2["Soft Wins"].str.split(pat="-", expand=True)
form_df2[["Heavy Starts", "Heavy Wins"]] = form_df2["horse record heavy"].str.split(pat=":", expand=True)
form_df2[["Heavy Wins", "HDrop", "HDrop1"]] = form_df2["Heavy Wins"].str.split(pat="-", expand=True)

form_df2[["1st Up Starts", "1st Up Wins"]] = form_df2["horse record first up"].str.split(pat=":", expand=True)
form_df2[["1st Up Wins", "1Drop", "1Drop1"]] = form_df2["1st Up Wins"].str.split(pat="-", expand=True)

form_df2[["2nd Up Starts", "2nd Up Wins"]] = form_df2["horse record second up"].str.split(pat=":", expand=True)
form_df2[["2nd Up Wins", "2Drop", "2Drop1"]] = form_df2["2nd Up Wins"].str.split(pat="-", expand=True)

columns = ['1Drop','1Drop1', "GDrop", "GDrop1", "SDrop", "SDrop1", "HDrop", "HDrop1", "RDrop", "RDrop1", "DDrop", "DDrop1", "TDrop", "TDrop1", "TDDrop", "TDDrop1", "2Drop", "2Drop1"]
form_df2[columns] = form_df2[columns].astype(float)

form_df2['1st Up Placings'] = form_df2.loc[:,['1Drop','1Drop1']].sum(axis=1)
form_df2['2nd Up Placings'] = form_df2.loc[:,['2Drop','2Drop1']].sum(axis=1)
form_df2['Race Placings'] = form_df2.loc[:,['RDrop','RDrop1']].sum(axis=1)
form_df2['Dist Placings'] = form_df2.loc[:,['DDrop','DDrop1']].sum(axis=1)
form_df2['Track Placings'] = form_df2.loc[:,['TDrop','TDrop1']].sum(axis=1)
form_df2['Tr-Dist Placings'] = form_df2.loc[:,['TDDrop','TDDrop1']].sum(axis=1)
form_df2['Good Placings'] = form_df2.loc[:,['GDrop','GDrop1']].sum(axis=1)
form_df2['Soft Placings'] = form_df2.loc[:,['SDrop','SDrop1']].sum(axis=1)
form_df2['Heavy Placings'] = form_df2.loc[:,['HDrop','HDrop1']].sum(axis=1)

form_df2["horselast10"] = form_df2["horselast10"].convert_dtypes()
form_df2["horselast10"].dtype

form_df2['RFS'] = form_df2['horselast10'].str.split('x').str[-1]

form_df2['RFS_Count'] = form_df2['RFS'].str.count(r'\d')

form_df2[["Date", "Time"]] = form_df2["start time"].str.split(pat=" ", expand=True)

form_df2[["Last 600m", "SsDrop"]] = form_df2["sectional"].str.split(pat="s", expand=True)

form_df2.drop(['RDrop', 'RDrop1', 'DDrop', 'DDrop1', 'TDrop', 'TDrop1', 'TDDrop', 'TDDrop1', 'start time', "GDrop", "GDrop1", "SDrop", "SDrop1", "HDrop", "HDrop1", "1Drop", "1Drop1", "2Drop", "2Drop1", 'Minutes', 'Secs', 'Seconds',	'MSecs', 'RunTime', 'margin', 'MarginTime', 'SsDrop', 'sectional'], axis = 1, inplace = True)

columns = ['Race Wins', 'Race Starts', 'Dist Wins', 'Dist Starts', 'Track Wins', 'Track Starts', 'Tr-Dist Wins', 'Tr-Dist Starts' , 'Good Wins', 'Good Starts', 'Soft Wins','Soft Starts', 'Heavy Wins', 'Heavy Starts', "1st Up Starts", "1st Up Wins" , "2nd Up Starts", "2nd Up Wins", 'RFS_Count']
form_df2[columns] = form_df2[columns].astype(float)

form_df2['Dist SR'] = form_df2['Dist Wins']/form_df2['Dist Starts'] * 100
form_df2['Win SR'] = form_df2['Race Wins']/form_df2['Race Starts'] * 100
form_df2['Track SR'] = form_df2['Track Wins']/form_df2['Track Starts'] * 100
form_df2['Tr-Dist SR'] = form_df2['Tr-Dist Wins']/form_df2['Tr-Dist Starts'] * 100
form_df2['Good SR'] = form_df2['Good Wins']/form_df2['Good Starts'] * 100
form_df2['Soft SR'] = form_df2['Soft Wins']/form_df2['Soft Starts'] * 100
form_df2['Heavy SR'] = form_df2['Heavy Wins']/form_df2['Heavy Starts'] * 100
form_df2['1st Up SR'] = form_df2['1st Up Wins']/form_df2['1st Up Starts'] * 100
form_df2['2nd Up SR'] = form_df2['2nd Up Wins']/form_df2['2nd Up Starts'] * 100

form_df2 = form_df2.round(2)

form_df2['form meeting date'] =  pd.to_datetime(form_df2['form meeting date'])
form_df2['form meeting date'] = form_df2['form meeting date'].dt.strftime('%d-%m-%Y')
form_df2['form meeting date'] =form_df2['form meeting date'].apply(pd.to_datetime)
form_df2['DLR-1'] = (pd.to_datetime('today') - form_df2['form meeting date']).dt.days - btdays

form_df2.to_csv(f'./NewData/CleanedForm/{meeting} - Form.csv', index=0)
form_df2

,track,race number,distance,age restrictions,class restrictions,weight restrictions,sex restrictions,weight type,grade,horse name,...,Dist SR,Win SR,Track SR,Tr-Dist SR,Good SR,Soft SR,Heavy SR,1st Up SR,2nd Up SR,DLR-1
0,Cranbourne,1,1000,3yo,Maiden,0.0,NaN,Set Weight,NaN,I Miss Margie,...,0.00,0.00,NaN,NaN,0.00,0.0,0.00,0.00,0.0,12
5,Cranbourne,1,1000,3yo,Maiden,0.0,NaN,Set Weight,NaN,I'm Mim,...,0.00,0.00,NaN,NaN,0.00,0.0,NaN,0.00,0.0,215
8,Cranbourne,1,1000,3yo,Maiden,0.0,NaN,Set Weight,NaN,Sakowin,...,NaN,0.00,NaN,NaN,0.00,0.0,NaN,0.00,NaN,17
10,Cranbourne,1,1000,3yo,Maiden,0.0,NaN,Set Weight,NaN,Aye Aye Skipper,...,0.00,0.00,NaN,NaN,0.00,0.0,0.00,0.00,0.0,24
14,Cranbourne,2,1200,4yo+,Maiden,0.0,NaN,Set Weight,NaN,Beautiful View,...,0.00,0.00,NaN,NaN,0.00,0.0,0.00,0.00,0.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5838,Yarra Glen,9,1009,3yo+,Benchmark 58,54.0,NaN,Handicap,NaN,Onepointsevengone,...,5.56,10.00,NaN,NaN,5.56,0.0,28.57,0.00,0.0,26
5848,Yarra Glen,9,1009,3yo+,Benchmark 58,54.0,NaN,Handicap,NaN,Gracie Turf,...,25.00,7.69,NaN,NaN,20.00,0.0,0.00,25.00,0.0,197
5858,Yarra Glen,9,1009,3yo+,Benchmark 58,54.0,NaN,Handicap,NaN,Just Malcolm,...,9.09,5.00,NaN,NaN,0.00,20.0,0.00,16.67,0.0,14
5868,Yarra Glen,9,1009,3yo+,Benchmark 58,54.0,NaN,Handicap,NaN,Carry On Camping,...,5.56,3.33,33.33,33.33,6.25,0.0,0.00,25.00,0.0,6
5878,Yarra Glen,9,1009,3yo+,Benchmark 58,54.0,NaN,Handicap,NaN,Steady Jam,...,27.27,20.59,0.00,NaN,16.67,0.0,22.22,40.00,0.0,13

In [20]:

pfratings_path = r'./NewData/Ratings/'
pf_ratings = pd.read_csv(pfratings_path + f"{etd} - RatingsSheet.csv", index_col=False, header=0)

pf_field = pd.read_csv(f'./NewData/Fields/{etd} - Fields.csv', index_col=0)
pf_field.rename(columns={' Horse':'Horse', ' Tab Number':'Tab Number', ' Weight':'Weight', ' Claim':'Claim', ' Jockey':'Jockey', ' Trainer':'Trainer'}, inplace=True)

race = pd.merge(pf_field, pf_ratings, how='left',left_on=['Horse','Tab Number'],right_on=['HorseName','TabNo'])

race = race.reset_index(drop=True)
race.drop([' HorseId', ' TrainerId', ' FormId', ' Barrier', 'RaceNo', 'HorseName', 'TabNo'], axis=1, inplace=True)

pf_form = pd.read_csv(f'./NewData/CleanedForm/{etd}-{track} - Form.csv', index_col=0)

races = pd.merge(race, pf_form, how='left', left_on=['Horse', 'Tab Number', 'Meeting'], right_on=['horse name', 'horse number', 'track'])

races1 = pd.merge(races, form_df3, how='left', left_on=['Horse', 'Tab Number', 'Race Number'], right_on=['Horse', 'Tab Number', 'Race Number'])

races2 = pd.merge(races1, form_df6, how='left', left_on=['Horse', 'Tab Number', 'Race Number'], right_on=['Horse', 'Tab Number', 'Race Number'])

races2 = races2.dropna(axis=0, subset=['Barrier'])

races2.rename(columns={'form position':'Form Pos-1', 'form margin':'Form Margin-1', 'HorseName':'Horse', 'Tab Number':'Tab No', 'form price':'Form Price-1', 'TrackCondition':'Tr-Cond', 'Historical Run Style':'Hist Run Style', 'distance':'Distance', 'form track':'Form Track-1', 'form tack condition':'Form Tr Cond-1', 'form barrier':'Form Barrier-1', 'form distance':'Form Dist-1', 'Predicted Settling Position':'Pred Stlg Pos', 'horselast10':'Form Last 10', 'form weight':'Form Weight-1', 'form class':'Form Cl-1', 'form jockey':'Form Jky-1', 'form meeting date':'Form Mtg Date', 'form other runners':'Form Other Runners-1', 'form time':'Form Time-1', 'form track condition':'Form Tr-Cond-1', 'class restrictions':'Race Cl', 'horse record':'Horse Record', 'horse record track':'Record Track', 'horse record distance':'Record Dist', 'horse record track distance':'Record Trk-Dist', 'horse record firm':'Record Firm', 'horse record good':'Record Good', 'horse record soft':'Record Soft', 'horse record heavy':'Record Heavy', 'horse record first up':'First Up Record', 'horse record second up':'Second Up Record', ' RaceId':'RaceId'}, inplace=True)

races2.drop(['race number', 'horse name', 'horse number', 'horse barrier', 'horse jockey', 'horse trainer', 'horse weight', 'horse claim', 'form name', 'horse record jumps'], axis=1, inplace=True)

races2['Pred Stlg Pos'].replace('-',99, inplace=True)
races2['Neural Price'].replace('-',99, inplace=True)
races2['Class Change'].replace('-',99, inplace=True)

columns = ['Pred Stlg Pos', 'Dist SR', 'Neural Price', 'Class Change']
races2[columns] = races2[columns].astype(float)

races2['Wght Chg'] = races2['Weight'] - races2['Form Weight-1']
races2['Dist Chg'] = races2['Distance'] - races2['Form Dist-1']
races2['Bar Chg'] = races2['Barrier'] - races2['Form Barrier-1']

races2['Form Mtg Date'] =  pd.to_datetime(races2['Form Mtg Date'])
races2['Form Mtg Date'] = races2['Form Mtg Date'].dt.strftime('%d-%m-%Y')

cols = ['Time', 'Race Cl', 'Distance', 'Meeting', 'Tr-Cond']
races2[cols] = races2[cols].ffill(axis=0)

races2['DBR-1/2'] = races2['DLR-2'] - races2['DLR-1']
races2['DBR-2/3'] = races2['DLR-3'] - races2['DLR-2']

races2['Horse'] = races2['Horse'].str.replace(r"[\"\',]", '')
races2['Horse'] = races2['Horse'].str.title()

races2['Starters'] = (races2.groupby(["Meeting", "Race Number"])['Tab No'].transform('nunique'))

races3 = races2[['Meeting', 'Race Number', 'Distance', 'Tab No', 'Horse', 'HorseId', 'Weight', 'Barrier', 'Jockey', ' JockeyId', 'Trainer', 'Tr-Cond', 'Class Change', 'Hist Run Style', 'Pred Stlg Pos', 'Neural Rank', 'age restrictions', 'Race Cl', 'weight restrictions', 'sex restrictions', 'weight type', 'horse age', 'Race Starts', 'horse sex', 'Form Margin-1', 'Form Pos-1', 'Form Price-1', 'Starters']]

races3.rename(columns={'Tr-Cond': 'Trackcondition', 'Pred Stlg Pos':'Settling Pos', 'Neural Rank':'Neural', 'weight restrictions':'Limitweight', 'weight type':'Weighttype', 'horse age':'Age', 'horse sex':'Sex', 'Form Margin-1':'Margin', 'Form Pos-1':'LSFinPos', 'Form Price-1':'LSSP', 'HorseId':'Horseid', ' JockeyId':'Jockeyid', 'Race Starts':'Rno'}, inplace=True)

races2.to_csv('./NewData/%s.csv' %meeting, index=False)
races2.to_excel('./NewData/%s.xlsx' %meeting, index=False)
races2

,Race Number,Tab No,Horse,Weight,Claim,Jockey,Trainer,RaceId,JockeyId,Meeting,...,Form Track-3,Form Tr Cond-3,Form Weight-3,DLR-3,Wght Chg,Dist Chg,Bar Chg,DBR-1/2,DBR-2/3,Starters
0,1,1,Core Concept,58.0,0.0,Jamie Mott,Mark Ashby,1123361,13251,Cranbourne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,1,2,Dark Journey,58.0,0.0,Daniel Moor,Jason Warren,1123361,13066,Cranbourne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,1,4,Presides,58.0,0.0,Jye Mc Neil,James Cummings,1123361,14936,Cranbourne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,1,5,Abovethefrostline,56.0,0.0,B Mc Dougall,Marcus Fahler,1123361,15279,Cranbourne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4,1,7,I Miss Margie,56.0,0.0,Luke Currie,T Busuttin & N Young,1123361,11407,Cranbourne,...,Moonee Valley,Soft 5,54.5,146.0,0.0,0.0,4.0,17.0,117.0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,9,6,Zipitup,56.5,4.0,Beau Treloar,Thomas Conlan,1123481,17400,Yarra Glen,...,Yarra Glen,Soft 5,59.0,55.0,-4.5,-91.0,0.0,27.0,13.0,9
639,9,7,Tom The Star,58.0,2.0,Thomas Prebble,Matthew Cumani,1123481,17083,Yarra Glen,...,Bendigo,Soft 5,56.0,236.0,0.5,-91.0,1.0,30.0,191.0,9
640,9,8,Gold Manuka,59.5,0.0,Rhys Mc Leod,Jason Warren,1123481,11899,Yarra Glen,...,Pakenham,Good 4,59.0,287.0,-0.5,-91.0,6.0,62.0,11.0,9
641,9,12,Carry On Camping,55.0,0.0,Harry Grace,M R Sharp,1123481,15607,Yarra Glen,...,Penshurst,Heavy 8,55.5,27.0,0.5,9.0,8.0,14.0,7.0,9
642,9,13,Steady Jam,52.0,2.0,Lauren Burke,D P Dwyer,1123481,17378,Yarra Glen,...,Harden,Firm 2,66.0,55.0,-1.0,109.0,-6.0,13.0,29.0,9

In [21]:
races3.to_csv(f'./NewData/Test/{etd}-TestFile.csv', index=False)
races3

,Meeting,Race Number,Distance,Tab No,Horse,Horseid,Weight,Barrier,Jockey,Jockeyid,...,Limitweight,sex restrictions,Weighttype,Age,Rno,Sex,Margin,LSFinPos,LSSP,Starters
0,Cranbourne,1,NaN,1,Core Concept,986678,58.0,5,Jamie Mott,13251,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,Cranbourne,1,NaN,2,Dark Journey,980888,58.0,2,Daniel Moor,13066,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,Cranbourne,1,NaN,4,Presides,964782,58.0,6,Jye Mc Neil,14936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,Cranbourne,1,NaN,5,Abovethefrostline,975139,56.0,3,B Mc Dougall,15279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4,Cranbourne,1,1000.0,7,I Miss Margie,975511,56.0,9,Luke Currie,11407,...,0.0,NaN,Set Weight,3.0,5.0,Filly,0.5,2.0,1.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,Yarra Glen,9,1009.0,6,Zipitup,943011,56.5,8,Beau Treloar,17400,...,54.0,NaN,Handicap,5.0,21.0,Gelding,3.5,8.0,21.0,9
639,Yarra Glen,9,1009.0,7,Tom The Star,883324,58.0,2,Thomas Prebble,17083,...,54.0,NaN,Handicap,7.0,28.0,Gelding,5.0,11.0,17.0,9
640,Yarra Glen,9,1009.0,8,Gold Manuka,946253,59.5,7,Rhys Mc Leod,11899,...,54.0,NaN,Handicap,5.0,8.0,Mare,6.0,8.0,5.0,9
641,Yarra Glen,9,1009.0,12,Carry On Camping,940441,55.0,9,Harry Grace,15607,...,54.0,NaN,Handicap,5.0,30.0,Gelding,0.8,2.0,21.0,9
642,Yarra Glen,9,1009.0,13,Steady Jam,929556,52.0,3,Lauren Burke,17378,...,54.0,NaN,Handicap,6.0,34.0,Gelding,7.5,9.0,11.0,9

In [22]:
# Predicting code
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf
tf.random.set_seed(31415)
os.environ['PYTHONHASHSEED'] = str(31415)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
import warnings
warnings.filterwarnings("ignore")
import pickle as pk

# Load the saved model
model = tf.keras.models.load_model('my_model.h5')

# Load the pickled XGB model
with open('XGB.pkl', 'rb') as f:
    classifier = pk.load(f)

# Load the pickled XGB feature columns
with open('xgb_cols.pkl', 'rb') as f:
    xgb_cols = pk.load(f)

with open('LSTM_cols.pkl', 'rb') as f:
    LSTM_cols = pk.load(f)

with open('encoders.pkl', 'rb') as f:
    encs = pk.load(f)

def predict(X):
    xgb_preds = classifier.predict(X[xgb_cols])
    lstm_preds = model.predict(X).reshape(xgb_preds.shape)

    return (xgb_preds + lstm_preds) / 2

In [23]:
xgb_cols

['Margin',
 'Starters',
 'Settling Pos',
 'Neural',
 'Trackcondition',
 'Limitweight',
 'Distance',
 'Rno',
 'Weighttype',
 'LSSP',
 'LSFinPos',
 'Age']

In [24]:
LSTM_cols

Index(['Distance', 'Weight', 'Barrier', 'Jockeyid', 'Trackcondition',
       'Settling Pos', 'Neural', 'Limitweight', 'Weighttype', 'Age', 'Rno',
       'Sex', 'Margin', 'LSFinPos', 'LSSP', 'Starters'],
      dtype='object')

In [ ]:


btdays = 0
today = date.today()
rundate = today - timedelta(days=btdays)
dte = rundate.strftime('%d-%m-%Y')
etd = rundate.strftime('%Y-%m-%d')

tst_df_full = pd.read_csv(f'./NewData/Test/{etd}-TestFile.csv').dropna()

tst_df = tst_df_full.rename(columns={
    'Meeting': 'Meetingid',
    'Race Number': 'Raceid',
    'Race Cl': 'Class',
    'age restrictions': 'Agerestrictions',
    'sex restrictions': 'Sexrestrictions',
    'Tab No': 'Tabno'
})[LSTM_cols]

cat_cols = [col for col in tst_df.columns if tst_df[col].dtype == 'object']
for col in cat_cols:
    tst_df[col] = encs[col].transform(tst_df[col].astype(str))

tst_df_full['preds%'] = predict(tst_df) * 100
tst_df_full['preds%'][tst_df_full['preds%'] > 100] = 100
tst_df_full['preds%'][tst_df_full['preds%'] < 0] = 0

tst_df_full.to_csv(f'Predictions/{etd}-Predictions.csv', index=False)